config/routes.rb
require 'sidekiq/web'
Sidekiq::Web.set :session_secret, Rails.application.secrets[:secret_key_base]

Rails.application.routes.draw do

  get 'tweet/index'

  get 'home/index'

  resources :blogs, :only=>[:index, :show, :edit] do
    resources :comments, only: [:index, :create]
  end



  resources :photos, :only=>[:create]

  namespace :admin do
    resources :articles, except: [:show] do
      collection do
        post :preview
      end
    end
    resources :sessions, :only=>[:new, :create, :destroy]

    resources :weibos

    root "dashboard#index"
  end

  root 'blogs#index'

  get '/about' => 'home#index'

  get '/tweet' => 'tweet#index'


  # writer your routes here

  mount Sidekiq::Web => '/sidekiq'
  mount StatusPage::Engine => '/'
  #mount ActionCable.server => '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
require 'markdown'

class Article < ApplicationRecord
  has_many :comments
  validates :title, :presence=>true, :uniqueness=> true
  validates :content, :presence=>true, :length => { :minimum=> 30 }

  def content_html
    self.class.render_html(self.content)
  end

  def self.render_html(content)
    rd = CodeHTML.new
    md = Redcarpet::Markdown.new(rd, autolink: true, fenced_code_blocks: true)
    md.render(content)
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  validates_presence_of :article_id
end

app/models/photo.rb
require 'carrierwave/orm/activerecord'

class Photo < ApplicationRecord
  mount_uploader :image, ImageUploader
end

app/models/weibo.rb
class Weibo < ApplicationRecord
end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < ApplicationController
  layout 'layouts/admin'
  before_action :authericate_user!

  def new
    @article = Article.new
  end

  def edit
    @article = Article.find(params[:id])
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      flash[:success] = "创建博客成功"
      redirect_to admin_articles_path
    else
      flash[:error] = "创建失败"
      render :new
    end
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      flash[:success] = "更新博客成功"
      redirect_to admin_articles_path
    else
      flash[:error] = "更新博客失败"
      render :edit
    end
  end

  def index
    @articles = Article.all
  end

  def destroy
    @article = Article.find(params[:id])
    if @article.destroy
      flash[:success] = '删除成功'
    else
      flash[:error] = '删除失败'
    end
    redirect_to admin_articles_path
  end

  def preview
    # binding.pry
    render plain: Article.render_html(params[:content]|| "")
  end

  private
    def article_params
      params.permit(:title, :content)
    end
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < ApplicationController
  layout 'layouts/admin'
  before_action :authericate_user!

  def index
    @article_count = Article.all.size
    @weibo_count = Weibo.all.size
  end
end

app/controllers/admin/sessions_controller.rb
class Admin::SessionsController < ApplicationController
  layout 'layouts/admin'

  def new
  end

  def create
    if ENV['ADMIN_USER'].blank?
      flash.now[:error] = "未配置管理员"
      render :new
    elsif ENV['ADMIN_USER'] != params[:username]
      flash.now[:error] = "用户名错误"
      render :new
    elsif ENV['ADMIN_PASSWORD'] != params[:password]
      flash.now[:error] = '密码错误'
      render :new
    else
      flash[:notice] = '登录成功'
      session[:login] = true
      redirect_to admin_root_path
    end
  end

  def destroy
    session[:login] = nil
    redirect_to new_admin_session_path
  end
end

app/controllers/admin/weibos_controller.rb
class Admin::WeibosController < ApplicationController
  layout 'layouts/admin'
  before_action :authericate_user!

  def new
    @weibo = Weibo.new
  end

  def create
    @weibo = Weibo.new(weibo_params)
    puts weibo_params
    if @weibo.save
      flash[:success] = "发布成功"
      redirect_to admin_weibos_path
    else
      flash[:error] = "创建失败"
      render :new
    end
  end

  def index
    @weibos = Weibo.order(created_at: :desc).all
  end

  def destroy
    @weibo = Weibo.find(params[:id])
    if @weibo.destroy
      flash[:success] = "删除成功"
    else
      flash[:error] = "删除失败"
    end
    redirect_to admin_weibos_path
  end

  private
    def weibo_params
      puts params
      params.permit(:cnt, :img)
    end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :admin_username

  protected
  def authericate_user!
    unless session[:login]
      flash[:error] = '请先登录后台管理'
      cookies[:urlback] = request.original_url
      redirect_to new_admin_session_path
    end
  end

  def admin_username
    session[:login] && ENV['ADMIN_USER']
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  def index
    @articles = Article.order(created_at: :desc).all
  end

  def show
    @article = Article.find(params[:id])
    @comments = @article.comments
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
  end

  def create
    @article = Article.find(params[:blog_id])
    @comment = @article.comments.build(comment_params)
    if @comment.save
      flash[:success] = "评论成功"
    else
      flash[:error] = "评论失败"
    end
    @comments = @article.comments
    # redirect_to blog_path(@article)
    render 'blogs/create'
  end

  private
    def comment_params
      params.permit(:name, :email, :cnt)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def create
    @photo = Photo.new(image: params["Filedata"])
    @photo.save!
    render plain: @photo.image.medium.url
  end

  private
    def md_url(url)
      "![](#{url})"
    end
end

app/controllers/tweet_controller.rb
class TweetController < ApplicationController
  def index
    @weibos = Weibo.order(created_at: :desc).all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def format_datetime(datatime)
    if datatime.blank?
      return ''
    end
    datatime.strftime("%Y.%m.%d %H:%M:%S")
  end

  def format_date(date)
    date.strftime("%Y.%m.%d")
  end
end

app/views/admin/articles/_form.html.slim
- url = @article.new_record? ? admin_articles_path : admin_article_path(@article)
= simple_form_for(@article, url: url, html: {novalidate: ''}) do |f|
  .row
    .col-md-6
      = f.input :title, label: '标题', input_html: {name: 'title'}
  ul.nav.nav-tabs
    li.content-title.active
      a href="#" 正文
    li.preview-title
      a href="#" 预览
    = link_to '上传图片', "#", :id=>'upload_photo'
  input type="file" style="display: none;"

    /= f.file_field :image, :label=>'', input_html: {id: 'upload_photo'}
  .tab-content#tabs
    .tab-pane.active#content
      = f.input :content, :as=> :text, :label=>false, input_html: {name: 'content', id: 'content-input'}
    .tab-pane.preview.markdown#preview
  .row
    .col-sm-12.col-lg-6
      button.btn.btn-primary.btn-lg type="submit" 提交

app/views/admin/articles/edit.html.slim
.row
  .col-sm-12
    h3 修改文章
    hr
    = render 'form'

app/views/admin/articles/index.html.slim
.row
  .col-sm-12
    h3 博客管理
    hr
    table.table
      thead
        tr
          th 文章名
          th 发表时间
          th 操作
      tbody
        -@articles.each do |article|
          tr
            td = link_to article.title, blog_path(article.id)
            td = format_datetime article.created_at
            td
              = link_to '编辑', edit_admin_article_path(article), class: 'edit-article-link'
              = link_to '删除', admin_article_path(article.id), method: :delete, data: {confirm: "确认删除?"}

app/views/admin/articles/new.html.slim
.row
  .col-sm-12
    h3 新建博客
    hr
    = render 'form'

app/views/admin/dashboard/index.html.slim
.row
  .col-sm-12
    h2 系统信息
    hr
    table.table.table-striped
      thead
        tr
          th 信息
          th 数据
      tbody
        tr.info
          td 文章数
          td #{@article_count}
        tr.info
          td 说说数
          td #{@weibo_count}

app/views/admin/weibos/_form.html.slim
- url = @weibo.new_record? ? admin_weibos_path : admin_weibo_path(@weibo)
= simple_form_for(@weibo, url: url, html: {novalidate: ''}) do |f|
  .row
    .col-md-4
      = f.input :img, label: '图片', input_html: {name: 'img', id: 'img-input'}
    .col-md-2
      = link_to '选择图片', "#", :id => 'select_photo'
  .row
    .col-md-8
      input type='file' style='display: none;'
      = f.input :cnt, :as => :text, :label => false, input_html: {name: 'cnt', id: 'cnt-input'}
  .row
    .col-sm-12.col-lg-6
      button.btn.btn-primary.btn-lg type="submit" 提交

app/views/admin/weibos/index.html.slim
.row
  .col-sm-12
    h3 Tweet管理
    hr
    table.table
      thead
        tr
          th 发布内容
          th 创建时间
          th 操作
      tbody
        - @weibos.each do |weibo|
          tr
            td
              = link_to truncate(weibo.cnt, length: 30), "/tweet#w_#{weibo.id}"
            td
              = format_datetime weibo.created_at
            td
              = link_to '删除', admin_weibo_path(weibo.id), method: :delete, data: {confirm: "确认删除?"}

app/views/admin/weibos/new.html.slim
.row
  .col-sm-12
    h3 发布Tweet
    hr
    = render 'form'

app/views/blogs/_comments.html.slim
.comments_wrap
  h2 评论列表
  .tweet
    -  if @comments.empty?
      p 暂无评论
    - else
      - @comments.each do |comment|
        p
          i #{comment.name}发表于#{format_date comment.created_at}
          | #{comment.cnt}

  h2 添加评论
  .row
    .col-sm-12.col-lg-8
      = simple_form_for(Comment.new, url: blog_comments_path(@article.id), html: {novalidate: ''}, remote: true) do |f|
        .row
          .col-sm-12.col-lg-8
            = f.input :name, label: '昵称', input_html: {name: 'name'}
        .row
          .col-sm-12.col-lg-8
            = f.input :email, label: '邮箱', input_html: {name: 'email'}
        .row
          .col-sm-12.col-lg-8
            = f.input :cnt, as: :text, label: '回复内容', input_html: {name: 'cnt'}
        button.btn.btn-primary.btn-lg type='submit' 提交回复

app/views/blogs/create.js.erb
$(".comments_wrap").replaceWith("<%= j render 'blogs/comments' %>")

app/views/blogs/index.html.slim
- content_for(:title) do
  | 首页
div style="margin: 5% 10% 2% 10%"
  table style="width: 100%"
    tr
      td style="width: 70%"
        ul.list-group 
          - @articles.each do |article|
            li.list-group-item.title
              = link_to article.title, blog_path(article)

app/views/blogs/show.html.slim
- content_for(:title) do
  | #{@article.title}

div.content style="margin: 2% 5% 2% 5%"
  table
    tr
      td width="60%"
        div.markdown style="padding: 2% 8% 5% 8%; border: 1px solid LightGrey;"
          h2 #{@article.title}
          == @article.content_html
          /br
          /= render 'comments'
      td width="16%"

app/views/home/index.html.slim
<div style=" text-align:center; height:30px; vertical-align:bottom font-size:50px">
<h1>DUZHENGZHI</h1>
br
<p>人间有味是清欢<p>
</div>

br
br
br
br
br
br
br
br
br
br
br
br
br
br
br
br
br
br
br
br
br



<div style=" text-align:center; height:30px; vertical-align:bottom">
<a href="http://www.weibo.com/duzhengzhi" title="Contact me"> 微博    </a> &nbsp
<a href="http://www.jianshu.com/u/6c5f0e206518" title="Contact me"> 简书    </a> &nbsp
<a href="https://github.com/DUZHENGZHI" title="@杜铮志 的 Github" target="_blank"> Github </a>&nbsp
<a href="mailto:duzhengzhi@foxmail.com" title="Contact me"> Email  </a> &nbsp
</div>

app/views/layouts/_admin_navbar.html.slim
nav.navbar.navbar-inverse role="navigation"
  .container-fluid
    .navbar-header
      button.navbar-toggle.collapsed type="button" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"
        span.sr-only
          | Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to "管理后台", admin_root_path, class: "navbar-brand"

    .collapse.navbar-collapse#bs-example-navbar-collapse-1
      ul.nav.navbar-nav
        li
          = link_to "发布Tweet", new_admin_weibo_path
        li
          = link_to "Tweet管理", admin_weibos_path
        li
          = link_to "新建博客", new_admin_article_path
        li
          = link_to "博客管理", admin_articles_path
      ul.nav.navbar-nav.navbar-right
        li
          = link_to "返回首页", root_path
        - if admin_username
          li
            = link_to admin_username + ' [ 退出 ] ', admin_session_path(1), method: :delete

app/views/layouts/_navbar.html.slim
nav.navbar.navbar-default role="navigation"
  .container-fluid
    .navbar-header
      button.navbar-toggle.collapsed type="button" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"
        span.sr-only
          | Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar

      = link_to "", root_path, class: "navbar-brand"

    .collapse.navbar-collapse#bs-example-navbar-collapse-1
      ul.nav.navbar-nav.navbar-right

        li
          = link_to "首页", root_path
        li
          = link_to "Tweet", tweet_path
        li
          = link_to "关于我", about_path

app/views/layouts/admin.html.slim
doctype html
html
  head
    meta charset='utf-8'
    meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"
    meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"
    meta name="renderer" content="webkit"
    title Admin Page
    = csrf_meta_tags
    = action_cable_meta_tag
    = content_for?(:head) ? yield(:head) : ''
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = favicon_link_tag "favicon.png"
  body
    = render "layouts/admin_navbar"

    -flash.each do |key, value|
      div class="alert alert-#{ key == 'error' ? 'danger' : 'success' } alert-dismissible"
        button.close type="button" data-dismiss="alert"
          span aria-hidden="true"
            |&times;
          span.sr-only
            |Close
        = value
    main
      .container
        == yield

app/views/layouts/application.html.slim
doctype html
html
  head
    meta charset='utf-8'
    meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"
    meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"
    meta name="renderer" content="webkit"
    meta http-equiv="cleartype" content="on"
    meta name="HandheldFriendly" content="True"
    meta name="MobileOptimized" content="320"
    title
      = content_for?(:title) ? yield(:title) : "xd"
    = csrf_meta_tags
    = action_cable_meta_tag
    = content_for?(:head) ? yield(:head) : ''
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = favicon_link_tag "favicon.png"
  body.view
    = render "layouts/navbar"
    main
      
        == yield

app/views/pages/about.html.slim
.container.text-center
  h1 About Page
  hr
  p This is an example for about page, using `high_voltage`
  br
  br
  br
  = link_to 'Back to Home', root_path

app/views/tweet/index.html.slim
- content_for(:title) do
  | Tweet

div.content style="margin: 2% 5% 2% 5%"
  table style="width: 100%"
    tr
      td style="width: 60%"
        div.markdown style="padding: 2% 8% 5% 8%; border: 1px solid LightGrey;"
          h3 我的Tweet
          .tweet
            - @weibos.each do |weibo|
              p id="w_#{weibo.id}"
                i #{format_datetime weibo.created_at}
                | #{weibo.cnt}
                - unless weibo.img.empty?
                  br
                  img src="#{weibo.img}"
      td width="16%"

app/views/visitors/index.html.slim
.container.text-center
  h1 Hello World
  hr
  h3 You are roading on Rails...
  br
  br
  br
  br
  p.text-muted From rails-template of 80percent!!

  = link_to 'About Page', page_path('about')